apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
      - name: devops-backend
        
        image: mohamedalichibani0110/devops-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
spec:
  # ICI : On utilise NodePort pour Minikube
  type: NodePort
  selector:
    app: devops-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007